version: "3.3"

services:
  portfolio-lorys-nginx:
    image: node:20.11.0
    container_name: portfolio-lorys-node
    restart: always
    networks:
      - traefik_network
    volumes:
      - ./app:/app
    command: node /app/server/index.mjs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-lorys.rule=Host(`lorys-mallet.com`)"
      - "traefik.http.routers.portfolio-lorys.entrypoints=web, websecure"
      - "traefik.http.routers.portfolio-lorys.tls=true"
      - "traefik.http.routers.portfolio-lorys.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio-lorys.loadbalancer.server.port=3000"

networks:
  traefik_network:
    external: true
